# Generated by Django 4.2.3 on 2024-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_cr',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='name_cr',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
