# Generated by Django 4.2.3 on 2024-04-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_name_category_name_cr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='description_cr',
            field=models.TextField(default=1, verbose_name='Тавсифи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='description_uz',
            field=models.TextField(default=1, verbose_name='Tavsifi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cr',
            field=models.CharField(max_length=255, verbose_name='Туркум'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, verbose_name='Categorya'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_cr',
            field=models.CharField(max_length=255, verbose_name='Таом номи'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_uz',
            field=models.CharField(max_length=255, verbose_name='Taom nomi'),
        ),
    ]
