# Generated by Django 4.2.3 on 2024-04-22 20:49

import django.core.validators
from django.db import migrations, models
import foods.models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_food_description_food_description_cr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='foods/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), foods.models.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cr',
            field=models.CharField(max_length=50, verbose_name='Туркум'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=50, verbose_name='Categorya'),
        ),
    ]
