from . import start
from . import get_chat_id
from . import handler
from . import delivery
from . import settings
from . import comments
from . import registrations
from . import order
from . import backet
from . import Take
